// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2WaGCmo4SOQnSBaY1uFx413-uaulcus',
    appId: '1:568431479228:web:c83a52b56049ae29c603b9',
    messagingSenderId: '568431479228',
    projectId: 'sri-movil-nueva',
    authDomain: 'sri-movil-nueva.firebaseapp.com',
    databaseURL: 'https://sri-movil-nueva.firebaseio.com',
    storageBucket: 'sri-movil-nueva.appspot.com',
    measurementId: 'G-JLX0HVSGQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7duVwr4OpCM3ArnXSAv681GUqJ0-Zgfo',
    appId: '1:568431479228:android:cb26c3dd983b4b26c603b9',
    messagingSenderId: '568431479228',
    projectId: 'sri-movil-nueva',
    databaseURL: 'https://sri-movil-nueva.firebaseio.com',
    storageBucket: 'sri-movil-nueva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNb0XNranmqQ49EScMTQzxa_ELxNEe8RE',
    appId: '1:568431479228:ios:59fb926415d69b8fc603b9',
    messagingSenderId: '568431479228',
    projectId: 'sri-movil-nueva',
    databaseURL: 'https://sri-movil-nueva.firebaseio.com',
    storageBucket: 'sri-movil-nueva.appspot.com',
    iosClientId: '568431479228-a9ig0p9b4h2601kodeh0ima1fa3o7i7e.apps.googleusercontent.com',
    iosBundleId: 'ec.gob.sri.movil.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNb0XNranmqQ49EScMTQzxa_ELxNEe8RE',
    appId: '1:568431479228:ios:59fb926415d69b8fc603b9',
    messagingSenderId: '568431479228',
    projectId: 'sri-movil-nueva',
    databaseURL: 'https://sri-movil-nueva.firebaseio.com',
    storageBucket: 'sri-movil-nueva.appspot.com',
    iosClientId: '568431479228-a9ig0p9b4h2601kodeh0ima1fa3o7i7e.apps.googleusercontent.com',
    iosBundleId: 'ec.gob.sri.movil.app',
  );
}
